addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.22")
addSbtPlugin("io.spray"                  % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.15.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.9")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.9.3")
addSbtPlugin("com.sksamuel.scapegoat"   %% "sbt-scapegoat"       % "1.2.3")
addSbtPlugin("com.github.sbt"            % "sbt-git"             % "2.0.0")
