apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-kind.fullname" . }}-configmap
  labels:
    {{- include "hello-kind.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_PORT: {{ .Values.database.port | quote }}