apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ include "hello-kind.fullname" . }}-secret
  labels:
    {{- include "hello-kind.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  data:
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: {{ .Values.vault }}
        property: database.password
    - secretKey: DATABASE_USERNAME
      remoteRef:
        key: {{ .Values.vault }}
        property: database.username
